services:
  gmd_creator: #this is the main django app. Check django_db_setup.sh to create the admin and populate the database.
    container_name: gmd_creator
    build: .
    image: gmd_creator/gmd_creator
    ports:
      - "8000:8000"

    volumes: #these volumes were added for development purposes. Django can reload after file changes.
      - "./app/:/app"
      - ./static/media:/vol/app/media

    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

    environment:
      - DB_HOST=db
      - DB_NAME=pycsw
      - DB_USER=postgres
      - DB_PASS=mypass
    depends_on:
        db:
            condition: service_healthy

  # nginx: #Reverse proxy: provides an external URL for the containers. This is the MAIN entry point that actually responds on port 80.
  #   container_name: nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   #volumes:
  #   #- '${PWD}/configs/nginx_reverse_proxy.conf:/etc/nginx/conf.d/default.conf:ro'
  #   #- '/var/run/docker.sock:/tmp/docker.sock:ro'
  #   #- '/etc/apache2/ssl:/etc/nginx/certs'
  #   restart: always
  #   logging:
  #     options:
  #       max-size: 1g
  #   image: nginx
  #   depends_on: # NGINX will not run if the containers of the reverse proxy are not running.
  #     - gmd_creator
  #     - pycsw
  #
  gmd_editor: #this is the fronted app.
    image: gmd_editor/gmd_editor
    build:
      context: ./geometadata_editor
      dockerfile: Dockerfile
    environment:
        VITE_GMD_CREATOR_URL: "http://localhost:8000" #${VITE_APP_URL}
    ports:
      - "5173:5173"
    volumes: #these volumes were added for development purposes. Django can reload after file changes.
      - "./geometadata_editor/src/:/app/src"



  db: #Spatial database
        restart: always
        ports:
            - '5432:5432'
        user: root
        # POSTGIS VOLUME IS NOT CONFIGURED BECAUSE DATA FOLDER CANNOT BE INSIDE THE SRC FOLDER
        volumes:
            - './data/postgres:/var/lib/postgresql/data'
            #- './logs/postgres:/var/log/postgresql/'
            #- './configs/create_databases.sh:/docker-entrypoint-initdb.d/create_databases.sh'
        logging:
            options:
                max-size: 1g
        environment:
            POSTGRES_PASSWORD: mypass
            POSTGRES_USER: postgres
            POSTGRES_DB: pycsw
            PGDATESTYLE: "ISO, DMY"
            PGDATA: /var/lib/postgresql/data
        image: postgis/postgis
        command: ["postgres"] #, "-c", "logging_collector=on", "-c", "log_statement=none", "-c", "log_directory=/var/log/postgresql/"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            retries: 5
            start_period: 10s
        hostname: db

  pycsw:
    container_name: pycsw
    image: geopython/pycsw
    environment:
      PYCSW_SERVER_URL: http://localhost:8088
    ports:
      - 8088:8000
    volumes:
      - ./configs/pycsw.yml:/etc/pycsw/pycsw.yml
    depends_on:
        db:
            condition: service_healthy

volumes:
  db-data:
