[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
plugins = ["mypy_django_plugin.main"]

# [tool.django-stubs]
# django_settings_module = "myproject.settings"

[mypy.plugins.django-stubs]
django_settings_module = "app.geometadata_creator.settings"
