# Generated by Django 5.0.7 on 2024-07-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scale_denominator', models.IntegerField()),
                ('mi', models.CharField(max_length=10)),
                ('inomen', models.CharField(max_length=20)),
            ],
        ),
    ]
